version: '3.5'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data 
      - ./mosquitto/log:/mosquitto/log 
    networks:
      - broker_adapter 
    environment:
      FORWARD_PORT: 1883

  influxdb:
    build: ./influxdb
    ports:
      - 8086:8086
      - 8000:8000
    networks:
      - db_adapter
    volumes:
      - ./influxdb:/var/lib/influxdb 
      - ./influxdb/init.db/init.iql:/docker-entrypoint-initdb.d/ 
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=iotdb

  adapter:
    build: ./adapter
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - broker_adapter 
      - db_adapter 
    environment:
      FORWARD_HOST: mosquitto 

networks:
  broker_adapter:
    external: false
  db_adapter:
    external: false

